version: '3.8'


services:

  local-stack:
    image: localstack/localstack:3.0.2
    container_name: local-stack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,lambda
      - DEBUG=1
      - HOSTNAME=aws-local
      - HOSTNAME_EXTERNAL=aws-local
      - DEFAULT_REGION=us-east-1
    volumes:
      - 'localstack_data:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"

  db-postgres:
    image: postgres:15.5-alpine3.18
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=JeyCode
      - POSTGRES_PASSWORD=JeyCode
      - POSTGRES_DB=taskfile_sample_db
      - POSTGRES_HOST=db-postgres
      - POSTGRES_PORT=5432
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'

volumes:
  localstack_data:
    name: localstack_data
    driver_opts:
      type: bind
      o: bind
      device: '~/workspace/docker-res/volumes/localstack'
  postgresql_data:
    name: postgresql_data
    driver_opts:
      type: bind
      o: bind
      device: '~/workspace/docker-res/volumes/postgresql'